# src/config.yaml
spatial:
  height: 159
  width: 181
  crs: "SR-ORG:6842"

paths:
  raw_dir: "data/raw"
  static_dir: "data/static"
  processed_dir: "data/processed"
  
  ndvi_template: "data/raw/NDVI_2006_01.tif"
  twi: "data/static/TWI.tif"
  soil_raster: "data/static/Soil_DSMW.tif"

features:
  train_split_year: 2021
  mode: "dl"          # options: "baselines" or "dl"
  window_size: 12
  n_epochs: 50
  learning_rate: 0.001
  patience: 10